import os
from datetime import datetime
import streamlit as st
from pathlib import Path
from PIL import Image as PILImage
from health_crew.workflows import build_diagnosis_crew
from health_crew.config import OPENAI_MODEL, GOOGLE_API_KEY

st.set_page_config(
    page_title="Healthcare Diagnosis Support", 
    layout="wide",
    page_icon="🏥"
)

st.title("🏥 Healthcare Diagnosis Support System")
st.caption("AI-powered multi-agent medical diagnosis with imaging analysis")

with st.sidebar:
    st.header("⚙️ Configuration")
    
    # Check API keys
    openai_configured = bool(os.getenv("OPENAI_API_KEY"))
    google_configured = bool(GOOGLE_API_KEY)
    
    if openai_configured:
        st.success("✅ OpenAI API configured")
    else:
        st.error("❌ OpenAI API key missing")
    
    if google_configured:
        st.success("✅ Google AI (Gemini) configured")
    else:
        st.warning("⚠️ Google AI key missing (required for imaging)")
    
    st.divider()
    
    verbose = st.checkbox("Verbose mode", value=True)
    st.caption(f"LLM Model: {OPENAI_MODEL}")
    
    st.divider()
    
    st.info(
        "This tool provides AI-powered multi-agent diagnosis support using "
        "CrewAI with specialized agents for symptoms, history, treatment, "
        "referrals, safety, and medical imaging analysis."
    )
    
    st.warning(
        "⚠️ **DISCLAIMER**: This tool is for educational and informational "
        "purposes only. All analyses should be reviewed by qualified healthcare "
        "professionals. Do not make medical decisions based solely on this analysis."
    )

# Create two columns for layout
col1, col2 = st.columns([2, 1])

with col1:
    st.subheader("📋 Patient Information")
    with st.form("patient_input"):
        symptoms = st.text_area(
            "Primary symptoms *", 
            placeholder="e.g., fever, cough, fatigue, chest pain",
            height=100,
            help="Describe the patient's main symptoms"
        )
        demographics = st.text_input(
            "Demographics *", 
            placeholder="e.g., age 45, male",
            help="Patient age, gender, and other relevant demographics"
        )
        history = st.text_area(
            "Brief medical history", 
            placeholder="Previous conditions, surgeries, chronic illnesses",
            height=100
        )
        medications = st.text_input(
            "Current medications", 
            placeholder="e.g., aspirin, lisinopril, metformin"
        )
        allergies = st.text_input(
            "Allergies", 
            placeholder="e.g., penicillin, latex (leave blank if none)"
        )
        submitted = st.form_submit_button("🔍 Run Diagnosis", type="primary", use_container_width=True)

with col2:
    st.subheader("🩻 Medical Imaging (Optional)")
    uploaded_file = st.file_uploader(
        "Upload medical image",
        type=["jpg", "jpeg", "png", "dicom"],
        help="Upload X-ray, MRI, CT scan, or other medical images"
    )
    
    if uploaded_file is not None:
        try:
            image = PILImage.open(uploaded_file)
            st.image(image, caption="Uploaded Image", use_container_width=True)
            st.success("✅ Image ready for analysis")
        except Exception as e:
            st.error(f"Error loading image: {e}")
    else:
        st.info("📤 Upload a medical image for AI-powered radiological analysis")

# Results section
if submitted:
    if not symptoms or not demographics:
        st.error("⚠️ Please fill in at least symptoms and demographics")
    else:
        # Save uploaded image temporarily if provided
        image_path = None
        include_imaging = False
        
        if uploaded_file is not None:
            try:
                upload_dir = Path("temp_uploads")
                upload_dir.mkdir(exist_ok=True)
                image_path = upload_dir / f"medical_image_{uploaded_file.name}"
                
                image = PILImage.open(uploaded_file)
                image.save(image_path)
                include_imaging = True
                st.info(f"🩻 Medical imaging analysis enabled")
            except Exception as e:
                st.warning(f"Could not process image: {e}. Continuing without imaging.")
        
        inputs = {
            "symptoms": symptoms or "",
            "demographics": demographics or "",
            "history": history or "",
            "medications": medications or "",
            "allergies": allergies or "",
            "working_differential": "To be generated by Symptom Analyzer",
            "diagnosis_summary": "To be generated by previous steps",
            "proposed_medications": medications or "",
            "conditions": "From differential/diagnosis",
            "treatment_plan": "To be generated by Treatment Agent",
            "referral_plan": "To be generated by Referral Agent",
            "clinical_summary": "Consolidated output",
            "medical_image_path": str(image_path) if image_path else "No image provided",
        }

        try:
            # Set report date
            if 'report_date' not in st.session_state:
                st.session_state.report_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            
            with st.spinner("🤖 Running multi-agent diagnosis crew... This may take a few minutes."):
                crew = build_diagnosis_crew(verbose=verbose, include_imaging=include_imaging)
                result = crew.kickoff(inputs=inputs)
            
            st.success("✅ Analysis completed successfully!")
            st.divider()
            
            # Display formatted results
            st.markdown("# 📊 Medical Diagnosis Report")
            st.markdown(f"**Patient:** {demographics} | **Generated:** {st.session_state.report_date}")
            st.divider()
            
            # Parse and format the result
            result_text = ""
            if hasattr(result, 'raw'):
                result_text = result.raw
            elif hasattr(result, 'output'):
                result_text = result.output
            elif isinstance(result, str):
                result_text = result
            else:
                result_text = str(result)
            
            # Create tabs for organized display
            tab1, tab2, tab3 = st.tabs(["📋 Executive Summary", "📝 Detailed Report", "🔍 Technical Output"])
            
            with tab1:
                st.markdown("### 🎯 Key Findings")
                
                # Executive summary card
                with st.container():
                    st.markdown("""
                    <style>
                    .summary-card {
                        background-color: #f0f8ff;
                        padding: 20px;
                        border-radius: 10px;
                        border-left: 5px solid #1f77b4;
                    }
                    </style>
                    """, unsafe_allow_html=True)
                    
                    col_a, col_b = st.columns(2)
                    
                    with col_a:
                        st.metric("Chief Complaint", symptoms[:50] + "..." if len(symptoms) > 50 else symptoms)
                        st.metric("Patient Demographics", demographics)
                    
                    with col_b:
                        st.metric("Medications", medications if medications else "None reported")
                        st.metric("Allergies", allergies if allergies else "None reported")
                
                st.markdown("---")
                
                # Extract first few paragraphs as summary
                summary_lines = result_text.split('\n')[:10]
                summary = '\n'.join([line for line in summary_lines if line.strip()])
                st.markdown(summary)
                
                if include_imaging:
                    st.info("🩻 Medical imaging analysis included in this report")
            
            with tab2:
                st.markdown("### 📄 Complete Analysis")
                
                # Organize by sections if possible
                sections = {
                    "Symptom Analysis": "🔍",
                    "Medical History": "📋",
                    "Imaging Analysis": "🩻",
                    "Treatment Recommendations": "💊",
                    "Referral Assessment": "👨‍⚕️",
                    "Drug Safety": "⚠️",
                    "Follow-up Plan": "📅",
                    "Patient Instructions": "👤"
                }
                
                # Try to split by common section headers
                current_section = None
                section_content = {}
                
                for line in result_text.split('\n'):
                    # Check if line is a section header
                    is_header = False
                    for section_name, icon in sections.items():
                        if section_name.lower() in line.lower() and (line.startswith('#') or line.isupper()):
                            current_section = section_name
                            section_content[current_section] = []
                            is_header = True
                            break
                    
                    if not is_header and current_section:
                        section_content[current_section].append(line)
                
                # Display sections in expanders
                if section_content:
                    for section_name, icon in sections.items():
                        if section_name in section_content:
                            with st.expander(f"{icon} **{section_name}**", expanded=(section_name == "Symptom Analysis")):
                                content = '\n'.join(section_content[section_name])
                                st.markdown(content)
                else:
                    # Fallback: display full text
                    st.markdown(result_text)
                
                st.divider()
                
                # Visual indicators
                col1, col2, col3 = st.columns(3)
                with col1:
                    st.markdown("**🟢 Completed Tasks**")
                    st.progress(1.0)
                with col2:
                    st.markdown("**👥 Agents Involved**")
                    agent_count = 8 if include_imaging else 7
                    st.write(f"{agent_count} specialized agents")
                with col3:
                    st.markdown("**⏱️ Process**")
                    st.write("Sequential workflow")
            
            with tab3:
                st.markdown("### 🔧 Technical Details")
                st.code(result_text, language="markdown")
                
                with st.expander("📦 Raw JSON Output"):
                    st.json(str(result))
                
                with st.expander("🔍 Debug Information"):
                    st.write("**Crew Configuration:**")
                    st.write(f"- Verbose mode: {verbose}")
                    st.write(f"- Imaging enabled: {include_imaging}")
                    st.write(f"- Model: {OPENAI_MODEL}")
                    if include_imaging:
                        st.write(f"- Vision model: {GOOGLE_API_KEY[:20]}..." if GOOGLE_API_KEY else "Not configured")
            
            st.divider()
            
            # Download report button
            st.download_button(
                label="📥 Download Full Report",
                data=result_text,
                file_name=f"diagnosis_report_{demographics.replace(' ', '_')}.txt",
                mime="text/plain"
            )
            
            st.caption(
                "⚠️ **IMPORTANT DISCLAIMER**: This AI-generated analysis is for educational and informational "
                "purposes only. All medical decisions should be made in consultation with qualified healthcare "
                "professionals. Do not use this report as a substitute for professional medical advice, diagnosis, or treatment."
            )
            
            # Cleanup temp image
            if image_path and image_path.exists():
                try:
                    image_path.unlink()
                except:
                    pass
                    
        except Exception as e:
            st.error(f"❌ Failed to run diagnosis: {e}")
            with st.expander("🔍 View Error Details"):
                st.exception(e)
